### ISSUE TITLE
Fix import from accounts has 10-star rating setting enabled

### ISSUE THREAD

**Issue by okachanov** [KonH/LivelibExport#10]
If account has 10-star rating option enabled, data will be exported with "My Rating" range 1-10, which is not supported by Goodreads

**Comment by KonH** [comment]
@okachanov 
Thanks for that corner case! Could you please look at PR - https://github.com/KonH/LivelibExport/pull/11 and also give me your user name to check how it works on real data, will appreciate your assistance.

**Comment by okachanov** [comment]
Yes, shure.
https://www.livelib.ru/reader/germis/
