### ISSUE TITLE
Ошибка 503 от на при попытке экспортировать книгу "Морфий"

### ISSUE THREAD

**Issue by abivos** [KonH/LivelibExport#18]
Страница книги Морфий без аутентификации на сайте отдает ошибку 503
https://www.livelib.ru/book/1001510906 

Кажется это сознательное решение сайта, возможно это не единственная страница с такой проблемой.
Для обхода помогла бы возможность передать логин токен через куку в скрипт.

**Comment by KonH** [comment]
Выглядит как решение, а можно подробнее насчет этой куки?

**Comment by abivos** [comment]
К сожалению, для того чтобы быстро обойти проблему я не стал разбираться какое значение в куках отвечает за авторизацию на сервисе. Я просто захардкодал все куки которые нашел в запросах к сайту с помощью developer console браузера. Добавил их в скрипт page_loader.py в переменную headers в методе download_book_page_direct. Как быстрое решение - сработало.

**Comment by KonH** [comment]
Добавил возможность указывать заголовки, насколько я вижу такого варианта будет достаточно для загрузки таких страниц (оказалось, что это не такая уж и редкость)
