### ISSUE TITLE
Продолжает ли работать скрипт?

### ISSUE THREAD

**Issue by buildie** [KonH/LivelibExport#5]
При попытке воспользоваться сначала выдает неправильный урл. Лечится добавлением домена перед взятым урлом из html. После этого упирается в 403. Livelib ввел дополнительную защиту или это что-то временное?

**Comment by KonH** [comment]
Добрый день!
Спасибо за замеченную проблему с URL, поправил ее в репозитории.
Касательно процесса работы скрипта - у сервиса изменился CDN и стандартные запросы из urllib стали отваливаться как "зловредные", добавил дополнительный хэдер, чтобы это не происходило.
Посмотрите, заработал ли скрипт в вашем случае после этих правок?

**Comment by grv87** [comment]
Не работает после подключения Cloudflare DDos protection.

У меня получилось выкачать, задействовав https://github.com/FlareSolverr/FlareSolverr

**Comment by grv87** [comment]
@KonH, а у вас сейчас работает, без каких-то доработок?

**Comment by ffiona** [comment]
@grv87 а не подскажите как вы задействовали [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr)? Лайвлиб упорно считает, что я бот и скачиваются пустые страницы.

**Comment by KonH** [comment]
Похоже имеет смысл добавить интеграцию с ним напрямую в проект, раз видно что есть потребность (при указании отдельного флага скачивать бинарники и использовать для запросов)
@ffiona какую ОС используете? для Windows / Linux это сработает, но на macOS нужно будет собирать из исходников, там удобство под вопросом

**Comment by ffiona** [comment]
@KonH я как раз на macOS.

**Comment by KonH** [comment]
@ffiona ок, тогда попробуем решить дополнительной документацией, есть шанс этим занятся на этой неделе

**Comment by KonH** [comment]
@ffiona 
Попробуйте переключится на ветку [features/proxy_usage](https://github.com/KonH/LivelibExport/tree/features/proxy_usage), там текущая версия использования этого варианта:
- В документации указано как использовать FlareSolverr с помощью отдельного параметра `--proxy-host`
- Добавлено создание и завершение сессии, выполнение запросов через FlareSolverr API

Но либо у меня какие-то специфические условия либо этот подход не особо помогает - я периодически все равно ловлю страницу ожидания
Пока в отдельной ветке, если вам это решение поможет - замержу
Если нет - посмотрим что с этим еще можно сделать (возможно еще перенос кук авторизации имеет смысл)

**Comment by KonH** [comment]
Замержил в мастер

**Comment by ffiona** [comment]
@KonH Извиняюсь, новый год меня поглотил. Да, помогло, спасибо!
