### ISSUE TITLE
Изменить URL c сайта LiveLib (возникла ошибка при экспорте, отправляется запрос https://livelib.ruhttps://livelib.ru/book/*")

### ISSUE THREAD

**Issue by vasilisa-che** [KonH/LivelibExport#7]
Можно решить, например,
- заменив в файле read.html адреса страниц с абсолютных на относительные: `href="https://livelib.ru ` заменить на `href="`
- и, наверное, вернуть прежний вариант (`this.full_link = link`) в [book.py](https://github.com/KonH/LivelibExport/commit/554125b67c211d9d1d9cc59aa474426d05d98bb8#diff-fccb8ec4dc8d032f7727e4651f26b1b82a5d86f253ea931e1677ac5f715ffc46)

**Comment by KonH** [comment]
Спасибо за информацию!
Интересно, каким образом там оказались абсолютные ссылки. Сейчас попробовал скачать страницу заново (через копирование содержимого в Chrome DevTools, обычное сохранение как html не отдает полноценную страницу) и запустить скрипт - повторить не удалось, в элементах относительные ссылки вида /book/*.
Можете поделится тем методом которым вы получили страницу с такими ссылками?
Подготовлю пока правку чтобы оба варианта были рабочими.

**Comment by KonH** [comment]
Сделал правку, теперь ссылки формируются на основе ID книги, без прямого использования ссылки из элемента
@vasilisa-che проверьте, если не сложно, решило ли это вашу проблему

**Comment by vasilisa-che** [comment]
Извините, не заметила ответ.
Кажется, поняла, в чем у меня была проблема: копировала не исходный код, а целиком страницу через ctrl+s, где добавился домен :)
Проверила еще раз, все работает. Спасибо за помощь!
